apiVersion: v1
kind: Service
metadata:
  name: mysql-$NAME-service
spec:
  type: LoadBalancer
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysql-$NAME-deployment
