apiVersion: v1
kind: Service
metadata:
  name: backend-$NAME-service
spec:
  type: LoadBalancer
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    run: backend-$NAME-deployment
