version: '2'
services:
  backend:
    build: backend
    ports:
     - "9200:9200"
    environment:
     - MYSQL_IP=mysql
    links:
     - mysql
  mysql:
    build: mysql
    ports:
     - "3306:3306"